#!/bin/bash

clear
echo empezando instalacion

sleep 1

clear

echo "deb http://download.webmin.com/download/repository sarge contrib" >> /etc/apt/sources.list

wget -q http://www.webmin.com/jcameron-key.asc -O- | sudo apt-key add -

sudo apt-get update

sudo apt-get install webmin
